---

namespace: jupyter

jupyter:
  image:
    name: jupyter/all-spark-notebook
    tag: 29edefbcb06a

configMapFromFiles:
  - name: jupyter-config
    dir: files/jupyter
    pattern: "**.py"
    mount: /etc/jupyter

secrets:
  - name: jupyter-access
    toEnv: true
    values:
      JUPYTER_TOKEN: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08%
      JUPYTER_GATEWAY_HTTP_USER: jupyter
      JUPYTER_GATEWAY_HTTP_PWD: jupyterpass
      JUPYTER_LOGIN_PASS: testing

envVars: {}
  #JUPYTER_LISTEN_PORT: 8888
