{{- if gt ( len .Values.secrets ) 0 }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.namespace }}
data:
  {{- range $name, $value := $secret.values }}
    {{ $name }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}