{{- if gt ( len .Values.secrets ) 0 }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
data: {{ toYaml $secret.values | nindent 2 }}
{{- end }}
{{- end }}