---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: jupyter-all-spark-driver
spec:
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 29413
      targetPort: 8888
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: jupyter-all-spark
spec:
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: {{ if hasKey .Values.envVars "JUPYTER_LISTEN_PORT" }}{{ .Values.envVars.JUPYTER_LISTEN_PORT }}{{ else }}{{ print 8888 }}{{ end }}
      targetPort: {{ if hasKey .Values.envVars "JUPYTER_LISTEN_PORT" }}{{ .Values.envVars.JUPYTER_LISTEN_PORT }}{{ else }}{{ print 8888 }}{{ end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: jupyter-all-spark
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jupyter-all-spark
            port:
              number: {{ if hasKey .Values.envVars "JUPYTER_LISTEN_PORT" }}{{ .Values.envVars.JUPYTER_LISTEN_PORT }}{{ else }}{{ print 8888 }}{{ end }}
